### ISSUE TITLE
Ampersand in project folder fails

### ISSUE THREAD

**Issue by elliottkember** [beachio/anvilformac#10]

**Comment by pbrocker** [comment]
@elliottkember: Certain characters in a URL such as &,!,: are encoded so that the browser knows how to render them. Due to this Anvil will render & as %26 when passing it to the URL. Since Anvil uses pow to handle symlink/DNS. Pow does not render the %26 (&) back into the ASCII character. So I believe this is a pow issue and not a Anvil issue.

Anvil shows url's with & fine in its program. And does send those URL's correctly to the browser.
